slogan: "杜龙少的博客"

theme: bootstrap
inverse: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/sdvdxl
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/sdvdxl
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: atom.xml
fancybox: true
favicon: favorite.ico
duoshuo_shortname: sdvdxl

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false
